// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 15.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassFileGenerator.Core.Templates.CSharp.Class
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using ClassFileGenerator.Core.Meta.Words;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ClassTemplate : ClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 foreach(var usingDefinitions in usings){ 
            
            #line default
            #line hidden
            
            #line 8 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(usingDefinitions.ToText()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 9 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 10 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(usings.Any()){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 12 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 13 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public ");
            
            #line 15 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(isPartial){ 
            
            #line default
            #line hidden
            this.Write("partial ");
            
            #line 15 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 15 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(implementsSetting.HasAny){ 
            
            #line default
            #line hidden
            this.Write("        : ");
            
            #line 17 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(implementsSetting.HeadImplement));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   foreach(var elem in implementsSetting.TailImplement) { 
            
            #line default
            #line hidden
            this.Write("        , ");
            
            #line 19 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elem));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 21 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("    {");
            
            #line 22 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(fields.Any()){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 25 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 foreach(var field in fields){ 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.AccessLevel.ToText()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
if(field.IsReadonly){ 
            
            #line default
            #line hidden
            this.Write("readonly ");
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(field.Value != null){ 
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Value));
            
            #line default
            #line hidden
            
            #line 26 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 27 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"

   var isFirst = true;
   foreach(var method in methods){

            
            #line default
            #line hidden
            
            #line 33 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   if(!isFirst) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 35 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 36 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   isFirst = false; 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.AccessLevel.ToText()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(method.HasAnyGenerics){ 
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.GenericsList));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ArgumentsText));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 37 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(method.HasAnyGenericsWhere){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   foreach(var condition in method.GenericsWheres){ 
            
            #line default
            #line hidden
            this.Write("            where ");
            
            #line 40 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(condition));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 41 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 42 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 43 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 if(!method.HasAnyGenericsWhere) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 45 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 47 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 foreach(var line in method.Body){ 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 48 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 49 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 51 "D:\github\ClassFileGeneratorCSharp\ClassFileGenerator\Core\Templates\CSharp\Class\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
